### ISSUE TITLE
SublimeLinter 4 compatibility

### ISSUE THREAD

**Issue by braver** [ChisholmKyle/SublimeLinter-contrib-avr-gcc#1]
In SL4 `persist.get_syntax()` is moved to `util.get_syntax()`. Please update this plugin like so: https://github.com/SublimeLinter/SublimeLinter-coffeelint/pull/28/files

**Comment by ChisholmKyle** [comment]
Thank you for creating this issue. I've update the plugin. Please let me know if there are still outstanding issues.
